packages:
  - "packages/*"
allowBuilds:
  better-sqlite3: true
  edgedriver: false
  electron: true
  electron-chromedriver: true
  esbuild: true
  geckodriver: false
minimumReleaseAgeExclude:
  - '@vue/language-core@3.3.10'
  - vue-tsc@3.3.10
  - '@wdio/cli@9.31.1'
  - '@wdio/config@9.31.1'
  - '@wdio/dot-reporter@9.31.1'
  - '@wdio/globals@9.31.1'
  - '@wdio/local-runner@9.31.1'
  - '@wdio/mocha-framework@9.31.1'
  - '@wdio/protocols@9.31.1'
  - '@wdio/reporter@9.31.1'
  - '@wdio/runner@9.31.1'
  - '@wdio/spec-reporter@9.31.1'
  - '@wdio/types@9.31.1'
  - '@wdio/utils@9.31.1'
  - '@wdio/xvfb@9.31.1'
  - expect-webdriverio@6.0.5
  - webdriver@9.31.1
  - webdriverio@9.31.1
